### ISSUE TITLE
[Deployment] Deploy generated Docker Image to Cluster

### ISSUE THREAD

**Issue by aslotte** [aslotte/MLOps.NET#305]
**Is your feature request related to a problem? Please describe.**
Once #304 is completed, we need the ability to deploy that generated image to a cluster, e.g. in Azure or AWS.

**Describe the solution you'd like**
To be discussed, but we probably want to deploy the model to a namespace within the cluster that has the name of `{ExperimentName}/{DeploymentTargetName}` or alike.

**Comment by aslotte** [comment]
I'm doing some research on this topic. 
Here are some findings:
- We want to make it cloud agnostic using `kubectl`
- We can use `kubectl --kubeconfig` to specify a specific `kubecfg` file that points to a cluster
- The `kubecfg` file can be exported from e.g. Azure AKS and most likely from other providers
- We can create an extension e.g. `UseKubernetes(string pathToKubeCfg)` for the `MLOpsBuilder`
- We need to generate a Kubernetes manifest (`.yml` file) to define the deployment of the image
- We need to understand how we can provide access for the cluster to the container registry
- We can use `kubectl apply` to deploy the manifest

**Comment by aslotte** [comment]
We need to think about if we want to separate models into namespaces by either `DeploymentTarget` or `ExperimentName` (and then tag with the other one instead)

Regardless, we'll need to create a namespace before deploying

**Comment by aslotte** [comment]
Example yml file

```
apiVersion: v1
kind: Pod
metadata:
  name: {experimentName}
  labels:
    name: {experimentName}
spec:
  containers:
  - name: {experimentName}
    image: {imagePath with version}
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080

```

**Comment by aslotte** [comment]
We can run the `kubectl` command to create a image pull secret. We need to supply the docker user, password and server which we already have 

https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auth-kubernetes

**Comment by aslotte** [comment]
```
apiVersion: v1
kind: Pod
metadata:
  name: my-awesome-app-pod
  namespace: awesomeapps
spec:
  containers:
    - name: main-app-container
      image: myregistry.azurecr.io/my-awesome-app:v1
      imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - name: acr-secret
```
